-- Gearwright: dungeon drops seen in game, from GearwrightProbe loot logs.
-- Generated by tools/loot_from_probe.py. Do not edit by hand: rerun the tool
-- with more exports instead.
--
-- from: the NPC's name when it was targeted while looting; count: times seen.
local _, ns = ...

ns.Data.DUNGEON_LOOT = {
}
