-- Gearwright: dungeon loot and dungeon quest rewards for Forever.
--
-- Data from Forever Dungeon Journal 1.4.4 by Exehn, used with his permission
-- (given in game, 2026-10-04) on the condition that he is credited. Thank you, Exehn!
-- Generated by tools/fdj_import.py; do not edit by hand. When Forever Dungeon
-- Journal is installed, Gearwright reads its live data instead of this copy.
--
-- dungeons[name] = { level = "13-20",
--   bosses = { { name, trash = true?, loot = { { itemID, name, slot, quality } } } },
--   quests = { { id, name, faction, level, requires, rewards = { { itemID, name, quality } } } } }
local _, ns = ...

ns.Data.DUNGEON_JOURNAL = {
  source = "Forever Dungeon Journal 1.4.4 by Exehn",
  dungeons = {
    ["Blackfathom Deeps"] = {
      level = "22+",
      bosses = {
        { name = "Ghamoo-ra", loot = {
          { 6907, "Tortoise Armor", "Chest, Mail", 3 },
          { 6908, "Ghamoo-ra's Bind", "Waist, Cloth", 3 },
          { 273839, "Spiked Shell Band", "Finger", 3 },
          { 251382, "Plans: Protector's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 252801, "Pattern: Totemic Leather Hood", "Recipe, Leatherworking", 3 },
          { 253940, "Pattern: Filigreed Silky Leggings", "Recipe, Tailoring", 3 },
          { 253942, "Pattern: Filigreed Flame Leggings", "Recipe, Tailoring", 3 },
        } },
        { name = "Lady Sarevess", loot = {
          { 888, "Naga Battle Gloves", "Hands, Leather", 3 },
          { 3078, "Naga Heartpiercer", "Ranged, Bow", 2 },
          { 11121, "Darkwater Talwar", "Main Hand, Sword", 2 },
          { 252798, "Pattern: Brawler's Leather Hood", "Leatherworking Recipe", 3 },
          { 251382, "Plans: Protector's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 251383, "Plans: Acolyte's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 253944, "Pattern: Filigreed Shadow Leggings", "Recipe, Tailoring", 3 },
        } },
        { name = "Gelihast", loot = {
          { 6906, "Algae Fists", "Hands, Mail", 3 },
          { 6905, "Reef Axe", "Two-Hand, Axe", 3 },
          { 1470, "Murloc Skin Bag", "Bag", 1 },
          { 273840, "Cursed Murloc Eye", "Trinket", 3 },
          { 251375, "Plans: Veteran's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 251377, "Plans: Protector's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252820, "Pattern: Brawler's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252821, "Pattern: Trapper's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252825, "Pattern: Wisdom's Leather Leggings", "Recipe, Leatherworking", 3 },
          { 253978, "Pattern: Filigreed Silky Circlet", "Recipe, Tailoring", 3 },
          { 253980, "Pattern: Filigreed Flame Circlet", "Recipe, Tailoring", 3 },
          { 273141, "Blueprint: Fishing Rack", "Blueprint", 2 },
        } },
        { name = "Lorgus Jett", loot = {
          { 273843, "Fallenroot Longbow", "Ranged, Bow", 3 },
          { 273841, "Twilight Maul", "Two-Hand, Mace", 3 },
          { 273842, "Treacherous Treads", "Feet, Mail", 3 },
          { 253978, "Pattern: Filigreed Silky Circlet", "Recipe, Tailoring", 3 },
          { 253982, "Pattern: Filigreed Shadow Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Baron Aquanis", loot = {
          { 16782, "Strange Water Globe", "Quest Item", 1 },
          { 252822, "Pattern: Defender's Leather Kilt", "Recipe, Leatherworking", 3 },
          { 253980, "Pattern: Filigreed Flame Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Old Serra'kis", loot = {
          { 6901, "Glowing Thresher Cape", "Back, Cloth", 3 },
          { 6904, "Bite of Serra'kis", "One-Hand, Dagger", 3 },
          { 6902, "Bands of Serra'kis", "Wrist, Leather", 3 },
          { 251375, "Plans: Veteran's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252825, "Pattern: Wisdom's Leather Leggings", "Recipe, Leatherworking", 3 },
          { 253978, "Pattern: Filigreed Silky Circlet", "Recipe, Tailoring", 3 },
          { 253982, "Pattern: Filigreed Shadow Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Twilight Lord Kelris", loot = {
          { 1155, "Rod of the Sleepwalker", "Two-Hand, Staff", 3 },
          { 6903, "Gaze Dreamer Pants", "Legs, Cloth", 3 },
          { 273846, "Twilight Lord Girdle", "Waist, Mail", 3 },
          { 252820, "Pattern: Brawler's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252821, "Pattern: Trapper's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252822, "Pattern: Defender's Leather Kilt", "Recipe, Leatherworking", 3 },
          { 252823, "Pattern: Totemic Leather Leggings", "Recipe, Leatherworking", 3 },
          { 252825, "Pattern: Wisdom's Leather Leggings", "Recipe, Leatherworking", 3 },
          { 253982, "Pattern: Filigreed Shadow Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Aku'mai", loot = {
          { 6911, "Moss Cinch", "Waist, Leather", 3 },
          { 6910, "Leech Pants", "Legs, Cloth", 3 },
          { 6909, "Strike of the Hydra", "Two-Hand, Sword", 3 },
          { 251376, "Plans: Guard's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 251377, "Plans: Protector's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 251378, "Plans: Acolyte's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252821, "Pattern: Trapper's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252824, "Pattern: Stormrider's Leather Kilt", "Recipe, Leatherworking", 3 },
          { 253980, "Pattern: Filigreed Flame Circlet", "Recipe, Tailoring", 3 },
          { 253984, "Pattern: Filigreed Pearly Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 1454, "Axe of the Enforcer", "One-Hand, Axe", 3 },
          { 1481, "Grimclaw", "One-Hand, Axe", 3 },
          { 3413, "Doomspike", "One-Hand, Dagger", 3 },
          { 2567, "Evocator's Blade", "One-Hand, Dagger", 3 },
          { 3414, "Crested Scepter", "Main Hand, Mace", 3 },
          { 3415, "Staff of the Friar", "Two-Hand, Staff", 3 },
          { 2271, "Staff of the Blessed Seer", "Two-Hand, Staff", 3 },
          { 3417, "Onyx Claymore", "Two-Hand, Sword", 3 },
          { 1491, "Ring of Precision", "Finger", 3 },
          { 1486, "Tree Bark Jacket", "Chest, Cloth", 3 },
          { 3416, "Martyr's Chain", "Chest, Mail", 3 },
          { 2034, "Scholarly Robes", "Chest, Cloth", 3 },
        } },
      },
      quests = {
        { id = 971, name = "Knowledge in the Deeps", faction = "Alliance", level = 23, requires = 10, rewards = {
          { 6743, "Sustaining Ring", 2 },
        } },
        { id = 1275, name = "Researching the Corruption", faction = "Alliance", level = 24, requires = 18, rewards = {
          { 7003, "Beetle Clasps", 2 },
          { 7004, "Prelacy Cape", 2 },
          { 270021, "Staghide Armguards", 3 },
        } },
        { id = 1199, name = "Twilight Falls", faction = "Alliance", level = 25, requires = 20, rewards = {
          { 6998, "Nimbus Boots", 2 },
          { 7000, "Heartwood Girdle", 2 },
          { 270025, "Silvered Gauntlets", 3 },
        } },
        { id = 1200, name = "Blackfathom Villainy", faction = "Alliance", level = 27, requires = 18, rewards = {
          { 7001, "Gravestone Scepter", 3 },
          { 7002, "Arctic Buckler", 3 },
          { 270031, "Dark Ritual Leggings", 3 },
          { 270032, "Cultist's Armguards", 3 },
        } },
        { id = 6565, name = "Allegiance to the Old Gods", faction = "Horde", level = 26, requires = 17, rewards = {
          { 17694, "Band of the Fist", 3 },
          { 17695, "Chestnut Mantle", 3 },
        } },
        { id = 6561, name = "Blackfathom Villainy", faction = "Horde", level = 27, requires = 18, rewards = {
          { 7001, "Gravestone Scepter", 3 },
          { 7002, "Arctic Buckler", 3 },
          { 270031, "Dark Ritual Leggings", 3 },
          { 270032, "Cultist's Armguards", 3 },
        } },
        { id = 1806, name = "The Test of Righteousness", faction = "Alliance", level = 22, requires = 20, rewards = {
          { 6953, "Verigan's Fist", 3 },
        } },
      },
    },
    ["City of Dalaran"] = {
      level = "28-33",
      bosses = {
        { name = "Atrexis the Grave Knight", loot = {
        } },
        { name = "Arcane Anomaly", loot = {
        } },
        { name = "Fel Ancient", loot = {
        } },
        { name = "Unstable Sentinel", loot = {
          { 273046, "Guardian's Dualblade", "Weapon", 3 },
        } },
        { name = "Mana Wraith", loot = {
        } },
        { name = "Mana Devourer", loot = {
        } },
        { name = "Mana Elemental", loot = {
        } },
        { name = "Lyn the Ignored", loot = {
        } },
        { name = "Shade of the Archmage", loot = {
          { 273052, "Ponderous Orb", "Held In Off-hand", 3 },
        } },
      },
      quests = {
        { id = 92456, name = "A Green Sample", faction = "Alliance", level = 33, requires = 24, rewards = {
          { 279835, "Vine Pruner's Cloak", 3 },
          { 279836, "Thorn Protecting Girdle", 3 },
        } },
        { id = 92489, name = "Power Overwhelming", faction = "Alliance", level = 33, requires = 24, rewards = {
          { 251962, "Violet Sash", 3 },
          { 279849, "Runebound Gloves", 3 },
        } },
        { id = 96987, name = "Opportunistic Education", faction = "Horde", level = 33, requires = 24, rewards = {
          { 279845, "Item 279845", 3 },
          { 279846, "Item 279846", 3 },
        } },
        { id = 96988, name = "Source of Power", faction = "Horde", level = 33, requires = 24, rewards = {
          { 279847, "Unstable Power Core", 3 },
          { 279848, "Construct Cloak", 3 },
        } },
        { id = 96986, name = "The Grave Knight", faction = "Horde", level = 33, requires = 24, rewards = {
          { 251963, "Gravewalker Boots", 3 },
          { 251965, "Undead Knight's Bracers", 3 },
        } },
      },
    },
    ["Excavation Site: Wetlands"] = {
      level = "26-31",
      bosses = {
        { name = "Saltspine", loot = {
          { 273024, "Glinteye Slippers", "Feet, Cloth", 3 },
          { 273022, "Supple Bellyskin Leggings", "Legs, Leather", 3 },
          { 273023, "Saltscale Girdle", "Waist, Mail", 3 },
        } },
        { name = "Shadetooth", loot = {
          { 273025, "Raptorclaw Greaves", "Feet, Mail", 3 },
          { 273027, "Raptor's Gaze", "Held In Off-hand", 3 },
          { 273106, "Blueprint: Greenhouse", "Blueprint", 2 },
        } },
        { name = "Relic Guardian", loot = {
          { 273028, "Reliquary Mantle", "Shoulder, Mail", 3 },
          { 273029, "Golemsight Long Gun", "Ranged, Gun", 3 },
          { 273030, "Ring of Power Regulation", "Finger", 3 },
          { 270866, "Titan Relic", "Quest Item", 1 },
          { 273097, "Blueprint: Rock Garden", "Blueprint", 2 },
        } },
      },
      quests = {
        { id = 95682, name = "Open the Maw", faction = "Horde", level = 31, requires = 24, rewards = {
          { 271740, "Knife-Polishing Rag", 3 },
          { 271732, "Dirt-Heavy Bracers", 3 },
        } },
        { id = 95697, name = "Changing Tastes", faction = "Horde", level = 31, requires = 24, rewards = {
          { 280766, "Satchel of Potions", 3 },
          { 280805, "Serrated Raptor Claw", 3 },
        } },
        { id = 95646, name = "Horrors in the Highland", faction = "Alliance", level = 31, requires = 24, rewards = {
          { 271667, "Ironwood Destroyer", 3 },
          { 271670, "Curl of Life", 3 },
          { 271664, "Hornbeam Heft", 3 },
        } },
        { id = 95809, name = "Heartwoven", faction = "Alliance", level = 31, requires = 24, rewards = {
          { 1710, "Greater Healing Potion", 1 },
          { 3827, "Mana Potion", 1 },
        } },
        { id = 98824, name = "Prehistoric Prism", faction = "Alliance", level = 31, requires = 24, rewards = {
          { 271716, "Explorer's League Dustcover", 3 },
          { 271767, "Healer's Staff", 3 },
          { 271766, "Heavehammer", 3 },
        } },
        { id = 98823, name = "Earthen Echo", faction = "Horde", level = 31, requires = 24, rewards = {
          { 271766, "Heavehammer", 3 },
          { 271767, "Healer's Staff", 3 },
          { 271719, "Furs of the Earthen Ring", 3 },
        } },
        { id = 95795, name = "Fallen in the Fen", faction = "Alliance", level = 31, requires = 24, rewards = {
          { 271769, "Daewyn's Girdle", 3 },
          { 271768, "Songblade Stabilizer", 3 },
        } },
      },
    },
    ["Gnomeregan"] = {
      level = "29-38",
      bosses = {
        { name = "Grubbis", loot = {
          { 9445, "Grubbis Paws", "Hands, Mail", 3 },
        } },
        { name = "Viscous Fallout", loot = {
          { 9452, "Hydrocane", "Two-Hand, Staff", 3 },
          { 9453, "Toxic Revenger", "One-Hand, Dagger", 3 },
          { 9454, "Acidic Walkers", "Feet, Cloth", 3 },
        } },
        { name = "Electrocutioner 6000", loot = {
          { 9446, "Electrocutioner Leg", "Main Hand, Sword", 3 },
          { 9447, "Electrocutioner Lagnut", "Finger", 3 },
          { 9448, "Spidertank Oilrag", "Wrist, Cloth", 3 },
        } },
        { name = "Crowd Pummeler 9-60", loot = {
          { 9449, "Manual Crowd Pummeler", "Two-Hand, Mace", 3 },
          { 9450, "Gnomebot Operating Boots", "Feet, Leather", 3 },
        } },
        { name = "Mekgineer Thermaplugg", loot = {
          { 9458, "Thermaplugg's Central Core", "Off Hand, Shield", 3 },
          { 9459, "Thermaplugg's Left Arm", "Two-Hand, Axe", 3 },
          { 9461, "Charged Gear", "Finger", 3 },
          { 9492, "Electromagnetic Gigaflux Reactivator", "Head, Cloth", 3 },
        } },
        { name = "Dark Iron Ambassador", loot = {
          { 9455, "Emissary Cuffs", "Wrist, Mail", 3 },
          { 9456, "Glass Shooter", "Ranged, Gun", 3 },
          { 9457, "Royal Diplomatic Scepter", "Main Hand, Mace", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 9508, "Mechbuilder's Overalls", "Chest, Cloth", 3 },
          { 9491, "Hotshot Pilot's Gloves", "Hands, Cloth", 3 },
          { 9509, "Petrolspill Leggings", "Legs, Leather", 3 },
          { 9510, "Caverndeep Trudgers", "Feet, Mail", 3 },
          { 9487, "Hi-tech Supergun", "Ranged, Gun", 3 },
          { 9485, "Vibroblade", "One-Hand, Axe", 3 },
          { 9488, "Oscillating Power Hammer", "One-Hand, Mace", 3 },
          { 9486, "Supercharger Battle Axe", "Two-Hand, Axe", 3 },
          { 9490, "Gizmotron Megachopper", "Two-Hand, Sword", 3 },
          { 9489, "Gyromatic Icemaker", "Ranged, Wand", 3 },
        } },
      },
      quests = {
        { id = 2928, name = "Gyrodrillmatic Excavationators", faction = "Alliance", level = 30, requires = 20, rewards = {
          { 9608, "Shoni's Disarming Tool", 2 },
          { 9609, "Shilly Mitts", 2 },
          { 270045, "Operator's Gloves", 2 },
        } },
        { id = 2930, name = "Data Rescue", faction = "Alliance", level = 30, requires = 25, rewards = {
          { 9605, "Repairman's Cape", 2 },
          { 9604, "Mechanic's Pipehammer", 2 },
        } },
        { id = 2929, name = "The Grand Betrayal", faction = "Alliance", level = 35, requires = 25, rewards = {
          { 9623, "Civinad Robes", 2 },
          { 9624, "Triprunner Dungarees", 2 },
          { 9625, "Dual Reinforced Leggings", 2 },
        } },
        { id = 2843, name = "Gnomer-gooooone!", faction = "Horde", level = 35, requires = 20, rewards = {
          { 9173, "Goblin Transponder", 1 },
        } },
        { id = 2841, name = "Rig Wars", faction = "Horde", level = 35, requires = 25, rewards = {
          { 9623, "Civinad Robes", 2 },
          { 9624, "Triprunner Dungarees", 2 },
          { 9625, "Dual Reinforced Leggings", 2 },
        } },
        { id = 2904, name = "A Fine Mess", faction = "Both", level = 30, requires = 24, rewards = {
          { 9535, "Fire-welded Bracers", 2 },
          { 9536, "Fairywing Mantle", 2 },
          { 270042, "Technician's Bracers", 2 },
        } },
        { id = 2951, name = "The Sparklematic 5200!", faction = "Both", level = 30, requires = 25, rewards = {
          { 9363, "Sparklematic-Wrapped Box", 1 },
        } },
      },
    },
    ["Hall of Thanes"] = {
      level = "13-20",
      bosses = {
        { name = "Faldrim Anvilmar", loot = {
          { 270227, "Ephemeral Choker", "Neck", 3 },
          { 271096, "Aetherwisp Bracers", "Wrist, Cloth", 3 },
          { 271097, "Spiritwraith Drape", "Back, Cloth", 3 },
        } },
        { name = "Magmatus", loot = {
          { 270230, "Kindlegem Girdle", "Waist, Mail", 3 },
          { 270231, "Flamefist Grips", "Hands, Leather", 3 },
          { 271095, "Fang of Magmatus", "Main Hand, Dagger", 3 },
        } },
        { name = "Plunder", loot = {
          { 270228, "Golemheart Stave", "Two-Hand, Staff", 3 },
          { 271098, "Golemguard Chest", "Chest, Mail", 3 },
          { 270229, "Treads of the Protector Golem", "Feet, Mail", 3 },
        } },
        { name = "Durgen Dirgehammer", loot = {
          { 270256, "Durgen's Crescent Axe", "Main Hand, Axe", 3 },
          { 270260, "Direhammer Leggings", "Legs, Leather", 3 },
          { 270261, "Robes of the Disgraced Thane", "Chest, Cloth", 3 },
          { 274286, "Durgen Dirgehammer's Head", "Quest Item", 1 },
        } },
      },
      quests = {
        { id = 96395, name = "An Ancient Grudge", faction = "Both", level = 15, requires = 10, rewards = {
          { 279899, "Catacomb Cloak", 3 },
          { 279900, "Deepgrave Trousers", 3 },
        } },
        { id = 96403, name = "Important Heirlooms", faction = "Both", level = 15, requires = 10, rewards = {
          { 279898, "Dwarven Tome", 3 },
          { 280096, "Tomb Robber's Gloves", 3 },
        } },
        { id = 96394, name = "The Restless Dead", faction = "Alliance", level = 15, requires = 10, rewards = {
          { 279897, "Dusty Belt", 3 },
          { 280095, "Cryptwalker Bracers", 3 },
        } },
        { id = 96393, name = "Old Ironforge Incursion", faction = "Alliance", level = 16, requires = 9, rewards = {
          { 279894, "Calibrated Blunderbuss", 3 },
          { 279895, "Ironforge Greathammer", 3 },
          { 279896, "Deepblaze", 3 },
        } },
      },
    },
    ["Ragefire Chasm"] = {
      level = "13-18",
      bosses = {
        { name = "Oggleflint", loot = {
          { 272999, "Barbaric Crossbow", "Ranged, Crossbow", 3 },
          { 272996, "Trogg Scepter", "Main Hand, Mace", 3 },
          { 272998, "Bone Knuckles", "Main Hand, Fist Weapon", 3 },
          { 252781, "Pattern: Stormrider's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
        } },
        { name = "Taragaman the Hungerer", loot = {
          { 14149, "Subterranean Cape", "Back, Cloth", 3 },
          { 14148, "Crystalline Cuffs", "Wrist, Cloth", 3 },
          { 14145, "Cursed Felblade", "Main Hand, Sword", 3 },
          { 251361, "Plans: Guard's Gloves", "Recipe, Blacksmithing", 3 },
          { 251362, "Plans: Protector's Gloves", "Recipe, Blacksmithing", 3 },
          { 251363, "Plans: Acolyte's Gloves", "Recipe, Blacksmithing", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
        } },
        { name = "Jergosh the Invoker", loot = {
          { 14150, "Robe of Evocation", "Chest, Cloth", 3 },
          { 14147, "Cavedweller Bracers", "Wrist, Mail", 3 },
          { 14151, "Chanting Blade", "One-Hand, Dagger", 3 },
          { 251360, "Plans: Veteran's Gloves", "Recipe, Blacksmithing", 3 },
          { 253906, "Pattern: Filigreed Flame Gown", "Recipe, Tailoring", 3 },
        } },
        { name = "Bazzalan", loot = {
          { 273003, "Searing Dagger", "Main Hand, Dagger", 3 },
          { 273007, "Chasm Walkers", "Feet, Leather", 3 },
          { 273005, "Satyrskin Cloak", "Back, Cloth", 3 },
          { 252780, "Pattern: Totemic Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 253908, "Pattern: Filigreed Shadow Gown", "Recipe, Tailoring", 3 },
          { 253910, "Pattern: Filigreed Pearly Gown", "Recipe, Tailoring", 3 },
        } },
      },
      quests = {
        { id = 5724, name = "Returning the Lost Satchel", faction = "Horde", level = 16, requires = 9, rewards = {
          { 15452, "Featherbead Bracers", 3 },
          { 15453, "Savannah Bracers", 3 },
          { 270003, "Garrison Cuffs", 3 },
        } },
        { id = 5725, name = "The Power to Destroy...", faction = "Horde", level = 16, requires = 9, rewards = {
          { 15449, "Ghastly Trousers", 3 },
          { 15450, "Dredgemire Leggings", 3 },
          { 15451, "Gargoyle Leggings", 3 },
        } },
      },
    },
    ["Razorfen Kraul"] = {
      level = "29-38",
      bosses = {
        { name = "Roogug", loot = {
          { 274155, "Geomancer Headdress", "Head, Leather", 3 },
          { 274152, "Roogug's Severed Head", "Trinket", 3 },
        } },
        { name = "Aggem Thorncurse", loot = {
          { 6681, "Thornspike", "One-Hand, Dagger", 3 },
          { 274158, "Death Prophet Spine", "Two-Hand, Staff", 3 },
          { 252820, "Pattern: Brawler's Leather Legguards", "Recipe, Leatherworking", 3 },
        } },
        { name = "Death Speaker Jargba", loot = {
          { 2816, "Death Speaker Scepter", "Main Hand, Mace", 3 },
          { 6685, "Death Speaker Mantle", "Shoulder, Cloth", 3 },
          { 6682, "Death Speaker Robes", "Chest, Cloth", 3 },
        } },
        { name = "Overlord Ramtusk", loot = {
          { 6687, "Corpsemaker", "Two-Hand, Axe", 3 },
          { 6686, "Tusken Helm", "Head, Mail", 3 },
          { 274161, "Quillord Mail Leggings", "Legs, Mail", 3 },
          { 251379, "Plans: Crusader's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252821, "Pattern: Trapper's Leather Legguards", "Recipe, Leatherworking", 3 },
        } },
        { name = "Agathelos the Raging", loot = {
          { 6691, "Swinetusk Shank", "Main Hand, Dagger", 3 },
          { 6690, "Ferine Leggings", "Legs, Leather", 3 },
          { 274160, "Quilrager Throwing Axe", "Thrown", 3 },
          { 251378, "Plans: Acolyte's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
        } },
        { name = "Charlga Razorflank", loot = {
          { 6693, "Agamaggan's Clutch", "Finger", 3 },
          { 6694, "Heart of Agamaggan", "Off Hand, Shield", 3 },
          { 6692, "Pronged Reaver", "One-Hand, Axe", 3 },
          { 273103, "Blueprint: Arcane Salvager", "Blueprint", 2 },
        } },
        { name = "Blind Hunter", loot = {
          { 6695, "Stygian Bone Amulet", "Neck", 3 },
          { 6697, "Batwing Mantle", "Shoulder, Cloth", 3 },
          { 6696, "Nightstalker Bow", "Ranged, Bow", 3 },
        } },
        { name = "Earthcaller Halmgar", loot = {
          { 6689, "Wind Spirit Staff", "Two-Hand, Staff", 3 },
          { 6688, "Whisperwind Headdress", "Head, Leather", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 776, "Vendetta", "One-Hand, Dagger", 3 },
          { 1727, "Sword of Decay", "Main Hand, Sword", 3 },
          { 1975, "Pysan's Old Greatsword", "Two-Hand, Sword", 3 },
          { 1976, "Slaghammer", "Two-Hand, Mace", 3 },
          { 2549, "Staff of the Shade", "Two-Hand, Staff", 3 },
          { 1978, "Wolfclaw Gloves", "Hands, Leather", 3 },
          { 2264, "Mantle of Thieves", "Shoulder, Leather", 3 },
          { 4438, "Pugilist Bracers", "Wrist, Mail", 3 },
          { 2039, "Plains Ring", "Finger", 3 },
        } },
      },
      quests = {
        { id = 1144, name = "Willix the Importer", faction = "Both", level = 30, requires = 23, rewards = {
          { 6748, "Monkey Ring", 2 },
          { 6750, "Snake Hoop", 2 },
          { 6749, "Tiger Band", 2 },
          { 274078, "Boar Signet", 3 },
        } },
        { id = 1142, name = "Mortality Wanes", faction = "Alliance", level = 30, requires = 25, rewards = {
          { 6751, "Mourning Shawl", 2 },
          { 6752, "Lancer Boots", 2 },
          { 270047, "Sentinel's Boots", 2 },
        } },
        { id = 1101, name = "The Crone of the Kraul", faction = "Alliance", level = 34, requires = 29, rewards = {
          { 4197, "Berylline Pads", 2 },
          { 6742, "Stonefist Girdle", 2 },
          { 6725, "Marbled Buckler", 2 },
        } },
        { id = 1102, name = "A Vengeful Fate", faction = "Horde", level = 34, requires = 29, rewards = {
          { 4197, "Berylline Pads", 2 },
          { 6742, "Stonefist Girdle", 2 },
          { 6725, "Marbled Buckler", 2 },
        } },
      },
    },
    ["Ruins of Lordaeron"] = {
      level = "15-22",
      bosses = {
        { name = "The Baron", loot = {
          { 271204, "Meathook Slicer", "One-Hand, Dagger", 3 },
          { 271205, "Abomination Bones", "Chest, Mail", 3 },
          { 271206, "Leftover Abomination Skin", "Chest, Cloth", 3 },
        } },
        { name = "Witherfang", loot = {
          { 271201, "Atrophic Girdle", "Waist, Mail", 3 },
          { 271202, "Witherbite Bracers", "Wrist, Leather", 3 },
          { 271203, "Segmented Spider Leg", "Two-Hand, Staff", 3 },
        } },
        { name = "The Abandoned", loot = {
          { 271207, "Rotmender's Leggings", "Legs, Cloth", 3 },
          { 271208, "Grip of Fear", "Hands, Mail", 3 },
          { 271216, "Scepter of the Abandoned", "Main Hand, Mace", 3 },
        } },
        { name = "Bjork", loot = {
          { 271209, "Bonerust Leggings", "Legs, Mail", 3 },
          { 271210, "Tuskwrap Belt", "Waist, Cloth", 3 },
          { 271217, "Corpse Chopper", "Two-Hand, Axe", 3 },
        } },
        { name = "Rath'mael", loot = {
          { 271213, "Mirror of Rath'mael", "Off Hand, Shield", 3 },
          { 271214, "Rotmender's Treads", "Feet, Cloth", 3 },
          { 271215, "Coldspire Staff", "Two-Hand, Staff", 3 },
          { 273085, "Blueprint: Fermenter", "Blueprint", 2 },
          { 273103, "Blueprint: Arcane Salvager", "Blueprint", 2 },
        } },
        { name = "Viktor the Vile", loot = {
          { 271211, "Vilewalkers", "Feet, Mail", 3 },
          { 271212, "Bloodied Chestwraps", "Chest, Leather", 3 },
          { 271218, "Vileblood Scimitar", "One-Hand, Sword", 3 },
        } },
        { name = "Lordaeron Captain", loot = {
          { 6641, "Haunting Blade", "Two-Hand, Sword", 3 },
          { 6642, "Phantom Armor", "Chest, Mail", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 286981, "Death Bindings", "Wrist, Mail", 3 },
          { 286977, "Sword of the Fallen", "Two-Hand, Sword", 3 },
          { 286978, "Rotmender's Garb", "Chest, Cloth", 3 },
          { 286980, "Rotmender's Sash", "Waist, Cloth", 3 },
        } },
      },
      quests = {
        { id = 95250, name = "Abominable Creatures", faction = "Alliance", level = 21, requires = 16, rewards = {
          { 279864, "Monstrous Cleaver", 3 },
          { 279865, "Grave Shroud", 3 },
          { 279867, "Slain Baron's Signet", 3 },
        } },
        { id = 97288, name = "Unending Torment", faction = "Horde", level = 21, requires = 16, rewards = {
          { 279864, "Monstrous Cleaver", 3 },
          { 279865, "Grave Shroud", 3 },
          { 279867, "Slain Baron's Signet", 3 },
        } },
        { id = 92401, name = "A Frightened Request", faction = "Horde", level = 22, requires = 15, rewards = {
          { 251485, "Edward's Knife", 3 },
          { 251486, "Tabitha's Cuffs", 3 },
        } },
        { id = 95195, name = "Bloodied Insignia", faction = "Alliance", level = 22, requires = 16, rewards = {
          { 279868, "Duty Bound Leggings", 3 },
          { 279869, "Remembrance Armor", 3 },
        } },
        { id = 95189, name = "Crest of Lordaeron", faction = "Alliance", level = 22, requires = 16, rewards = {
          { 280567, "Small Sack of Gems", 1 },
        } },
        { id = 95204, name = "Crest of Lordaeron", faction = "Horde", level = 22, requires = 16, rewards = {
          { 280567, "Small Sack of Gems", 1 },
        } },
        { id = 92421, name = "Light's Justice", faction = "Horde", level = 22, requires = 15, rewards = {
          { 279874, "The Stitcher", 3 },
          { 279875, "Spare Part Bindings", 3 },
        } },
        { id = 92415, name = "Remember That I Love You", faction = "Alliance", level = 22, requires = 15, rewards = {
          { 279870, "Tarnished Locket", 3 },
        } },
        { id = 95216, name = "The New Plague", faction = "Horde", level = 22, requires = 16, rewards = {
          { 279876, "Plaguefang", 3 },
          { 279877, "Blight Gloves", 3 },
        } },
        { id = 92422, name = "The Wrath of Rath'mael", faction = "Horde", level = 22, requires = 15, rewards = {
          { 251533, "Forsaken Greataxe", 3 },
          { 251534, "Gnarled Necromancer's Staff", 3 },
        } },
      },
    },
    ["Scarlet Monastery: Graveyard"] = {
      level = "30-38",
      bosses = {
        { name = "Interrogator Vishas", loot = {
          { 7682, "Torturing Poker", "One-Hand, Dagger", 3 },
          { 7683, "Bloody Brass Knuckles", "One-Hand, Fist Weapon", 3 },
          { 274290, "Painwalker Buckler", "Off Hand, Shield", 3 },
          { 252513, "Trapper's Leather Helm", "Head, Leather", 3 },
        } },
        { name = "Azshir the Sleepless", loot = {
          { 7709, "Blighted Leggings", "Legs, Cloth", 3 },
          { 7708, "Necrotic Wand", "Ranged, Wand", 3 },
          { 7731, "Ghostshard Talisman", "Neck", 3 },
        } },
        { name = "Fallen Champion", loot = {
          { 7691, "Embalmed Shroud", "Head, Cloth", 3 },
          { 7690, "Ebon Vise", "Hands, Leather", 3 },
          { 7689, "Morbid Dawn", "Two-Hand, Sword", 3 },
          { 252513, "Trapper's Leather Helm", "Head, Leather", 3 },
        } },
        { name = "Ironspine", loot = {
          { 7688, "Ironspine's Ribcage", "Chest, Mail", 3 },
          { 7687, "Ironspine's Fist", "One-Hand, Mace", 3 },
          { 7686, "Ironspine's Eye", "Finger", 3 },
        } },
        { name = "Bloodmage Thalnos", loot = {
          { 7685, "Orb of the Forgotten Seer", "Held In Off-hand", 3 },
          { 7684, "Bloodmage Mantle", "Shoulder, Cloth", 3 },
          { 274291, "Polished Skullcap", "Head, Mail", 3 },
          { 252822, "Pattern: Defender's Leather Kilt", "Recipe, Leatherworking", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 10328, "Scarlet Chestpiece", "Chest, Mail", 3 },
          { 10329, "Scarlet Belt", "Waist, Mail", 3 },
          { 10330, "Scarlet Leggings", "Legs, Mail", 3 },
          { 10331, "Scarlet Gauntlets", "Hands, Mail", 3 },
          { 10333, "Scarlet Wristguards", "Wrist, Mail", 3 },
          { 10332, "Scarlet Boots", "Feet, Mail", 3 },
          { 5819, "Sunblaze Coif", "Head, Mail", 3 },
          { 7730, "Cobalt Crusher", "Two-Hand, Mace", 3 },
          { 7761, "Steelclaw Reaver", "Main Hand, Axe", 3 },
          { 7787, "Resplendent Guardian", "Off Hand, Shield", 3 },
        } },
      },
      quests = {
        { id = 1051, name = "Vorrel's Revenge", faction = "Horde", level = 33, requires = 25, rewards = {
          { 7750, "Mantle of Woe", 2 },
          { 4643, "Grimsteel Cape", 2 },
        } },
      },
    },
    ["Shadowfang Keep"] = {
      level = "20-30",
      bosses = {
        { name = "Rethilgore", loot = {
          { 5254, "Rugged Spaulders", "Shoulder, Leather", 2 },
          { 273457, "Sorcerer Collar", "Neck", 3 },
          { 273456, "Cell Keeper's Claws", "Main Hand, Fist Weapon", 3 },
        } },
        { name = "Fel Steed / Shadow Charger", loot = {
          { 6341, "Eerie Stable Lantern", "Held In Off-hand", 3 },
          { 932, "Fel Steed Saddlebags", "Bag", 2 },
          { 251341, "Plans: Guard's Chain Shirt", "Recipe, Blacksmithing", 3 },
          { 251362, "Plans: Protector's Gloves", "Recipe, Blacksmithing", 3 },
          { 251363, "Plans: Acolyte's Gloves", "Recipe, Blacksmithing", 3 },
          { 251364, "Plans: Crusader's Gloves", "Recipe, Blacksmithing", 3 },
          { 252781, "Pattern: Stormrider's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 253902, "Pattern: Filigreed Pristine Gown", "Recipe, Tailoring", 3 },
          { 253904, "Pattern: Filigreed Silky Gown", "Recipe, Tailoring", 3 },
          { 253906, "Pattern: Filigreed Flame Gown", "Recipe, Tailoring", 3 },
          { 253908, "Pattern: Filigreed Shadow Gown", "Recipe, Tailoring", 3 },
          { 253910, "Pattern: Filigreed Pearly Gown", "Recipe, Tailoring", 3 },
          { 253912, "Pattern: Filigreed Shining Gown", "Recipe, Tailoring", 3 },
          { 251381, "Plans: Guard's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 251382, "Plans: Protector's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 252799, "Pattern: Trapper's Leather Hood", "Recipe, Leatherworking", 3 },
          { 252801, "Pattern: Totemic Leather Hood", "Recipe, Leatherworking", 3 },
          { 252803, "Pattern: Wisdom's Leather Hood", "Recipe, Leatherworking", 3 },
          { 253940, "Pattern: Filigreed Silky Leggings", "Recipe, Tailoring", 3 },
          { 253946, "Pattern: Filigreed Pearly Leggings", "Recipe, Tailoring", 3 },
          { 253948, "Pattern: Filigreed Shining Leggings", "Recipe, Tailoring", 3 },
        } },
        { name = "Razorclaw the Butcher", loot = {
          { 1292, "Butcher's Cleaver", "One-Hand, Axe", 3 },
          { 6226, "Bloody Apron", "Chest, Cloth", 3 },
          { 6633, "Butcher's Slicer", "One-Hand, Sword", 3 },
        } },
        { name = "Baron Silverlaine", loot = {
          { 6321, "Silverlaine's Family Seal", "Finger", 3 },
          { 6323, "Baron's Scepter", "Main Hand, Mace", 3 },
          { 273637, "Blade of Silverlaine", "Main Hand, Sword", 3 },
        } },
        { name = "Commander Springvale", loot = {
          { 6320, "Commander's Crest", "Off Hand, Shield", 3 },
          { 3191, "Arced War Axe", "Two-Hand, Axe", 3 },
          { 273643, "Worgenbane Talisman", "Trinket", 3 },
          { 6341, "Eerie Stable Lantern", "Held In Off-hand", 3 },
        } },
        { name = "Odo the Blindwatcher", loot = {
          { 6318, "Odo's Ley Staff", "Two-Hand, Staff", 3 },
          { 6319, "Girdle of the Blindwatcher", "Waist, Leather", 3 },
          { 273645, "Blindwatcher's Sight", "Head", 3 },
        } },
        { name = "Deathsworn Captain", loot = {
          { 6642, "Phantom Armor", "Chest, Mail", 3 },
          { 6641, "Haunting Blade", "Two-Hand, Sword", 3 },
        } },
        { name = "Arugal's Voidwalker", loot = {
          { 5943, "Rift Bracers", "Wrist, Mail", 3 },
        } },
        { name = "Fenrus the Devourer", loot = {
          { 6340, "Fenrus' Hide", "Back, Cloth", 3 },
          { 3230, "Black Wolf Bracers", "Wrist, Leather", 3 },
          { 273646, "Half-Eaten Boots", "Feet, Mail", 3 },
        } },
        { name = "Wolf Master Nandos", loot = {
          { 3748, "Feline Mantle", "Shoulder, Cloth", 3 },
          { 6314, "Wolfmaster Cape", "Back, Cloth", 3 },
          { 273647, "Worgpelt Leggings", "Legs, Leather", 3 },
        } },
        { name = "Archmage Arugal", loot = {
          { 6324, "Robes of Arugal", "Chest, Cloth", 3 },
          { 6392, "Belt of Arugal", "Waist, Cloth", 3 },
          { 6220, "Meteor Shard", "One-Hand, Dagger", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 1489, "Gloomshroud Armor", "Chest, Leather", 3 },
          { 1974, "Mindthrust Bracers", "Wrist, Cloth", 3 },
          { 1483, "Face Smasher", "One-Hand, Mace", 3 },
          { 2292, "Necrology Robes", "Chest, Cloth", 3 },
          { 2205, "Duskbringer", "Two-Hand, Sword", 3 },
          { 2807, "Guillotine Axe", "Main Hand, Axe", 3 },
          { 3194, "Black Malice", "Two-Hand, Mace", 3 },
          { 1482, "Shadowfang", "Main Hand, Sword", 3 },
          { 1935, "Assassin's Blade", "One-Hand, Dagger", 3 },
          { 1318, "Night Reaver", "Two-Hand, Axe", 3 },
          { 1484, "Witching Stave", "Two-Hand, Staff", 3 },
        } },
      },
      quests = {
        { id = 1098, name = "Deathstalkers in Shadowfang", faction = "Horde", level = 25, requires = 18, rewards = {
          { 3324, "Ghostly Mantle", 3 },
          { 270023, "Tanned Shoulderpads", 3 },
          { 270024, "Bronzed Shoulderguards", 3 },
        } },
        { id = 1740, name = "The Orb of Soran'ruk", faction = "Both", level = 25, requires = 20, rewards = {
          { 6898, "Orb of Soran'ruk", 3 },
          { 15109, "Staff of Soran'ruk", 3 },
        } },
        { id = 1013, name = "The Book of Ur", faction = "Horde", level = 26, requires = 16, rewards = {
          { 6335, "Grizzled Boots", 3 },
          { 4534, "Steel-clasped Bracers", 3 },
          { 270030, "Tattered Mittens", 3 },
        } },
        { id = 1014, name = "Arugal Must Die", faction = "Horde", level = 27, requires = 18, rewards = {
          { 6414, "Seal of Sylvanas", 3 },
        } },
        { id = 1806, name = "The Test of Righteousness", faction = "Alliance", level = 22, requires = 20, rewards = {
          { 6953, "Verigan's Fist", 3 },
        } },
      },
    },
    ["The Deadmines"] = {
      level = "17-26",
      bosses = {
        { name = "Rhahk'Zor", loot = {
          { 872, "Rockslicer", "Two-Hand, Axe", 3 },
          { 5187, "Rhahk'Zor's Hammer", "Two-Hand, Mace", 3 },
          { 273289, "Ogre Loincloth", "Legs, Cloth", 3 },
          { 251362, "Plans: Protector's Gloves", "Recipe, Blacksmithing", 3 },
          { 251364, "Plans: Crusader's Gloves", "Recipe, Blacksmithing", 3 },
          { 253906, "Pattern: Filigreed Flame Gown", "Recipe, Tailoring", 3 },
        } },
        { name = "Miner Johnson", loot = {
          { 5443, "Gold-plated Buckler", "Off Hand, Shield", 3 },
          { 5444, "Miner's Cape", "Back, Cloth", 3 },
        } },
        { name = "Sneed's Shredder", loot = {
          { 1937, "Buzz Saw", "One-Hand, Sword", 3 },
          { 2169, "Buzzer Blade", "Main Hand, Dagger", 3 },
          { 285292, "Dull Sawblade", "Thrown", 3 },
        } },
        { name = "Sneed", loot = {
          { 5194, "Taskmaster Axe", "Two-Hand, Axe", 3 },
          { 5195, "Gold-flecked Gloves", "Hands, Cloth", 3 },
          { 273293, "Bandsaw Wristbands", "Wrist, Mail", 3 },
          { 273092, "Blueprint: Repair Bot", "Engineering", 2 },
          { 251360, "Plans: Veteran's Gloves", "Recipe, Blacksmithing", 3 },
          { 251364, "Plans: Crusader's Gloves", "Recipe, Blacksmithing", 3 },
          { 253902, "Pattern: Filigreed Pristine Gown", "Recipe, Tailoring", 3 },
        } },
        { name = "Gilnid", loot = {
          { 1156, "Lavishly Jeweled Ring", "Finger", 3 },
          { 5199, "Smelting Pants", "Legs, Leather", 3 },
          { 273297, "Goblin Hammer", "Main Hand, Mace", 3 },
          { 252777, "Pattern: Brawler's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252778, "Pattern: Trapper's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252780, "Pattern: Totemic Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 253904, "Pattern: Filigreed Silky Gown", "Recipe, Tailoring", 3 },
          { 253906, "Pattern: Filigreed Flame Gown", "Recipe, Tailoring", 3 },
          { 273086, "Blueprint: Anvil", "Blueprint", 2 },
        } },
        { name = "Mr. Smite", loot = {
          { 7230, "Smite's Mighty Hammer", "Two-Hand, Mace", 3 },
          { 5192, "Thief's Blade", "One-Hand, Sword", 3 },
          { 5196, "Smite's Reaver", "One-Hand, Axe", 3 },
          { 284715, "First Mate Band", "Finger", 3 },
          { 251362, "Plans: Protector's Gloves", "Recipe, Blacksmithing", 3 },
          { 252779, "Pattern: Defender's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252780, "Pattern: Totemic Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252781, "Pattern: Stormrider's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252782, "Pattern: Wisdom's Leather Gloves", "Recipe, Leatherworking", 3 },
        } },
        { name = "Captain Greenskin", loot = {
          { 5201, "Emberstone Staff", "Two-Hand, Staff", 3 },
          { 10403, "Blackened Defias Belt", "Waist, Leather", 3 },
          { 5200, "Impaling Harpoon", "Two-Hand, Polearm", 3 },
        } },
        { name = "Edwin VanCleef", loot = {
          { 5193, "Cape of the Brotherhood", "Back, Cloth", 3 },
          { 5202, "Corsair's Overshirt", "Chest, Cloth", 3 },
          { 10399, "Blackened Defias Armor", "Chest, Leather", 3 },
          { 5191, "Cruel Barb", "One-Hand, Sword", 3 },
          { 2874, "An Unsent Letter", "Quest Item", 1 },
          { 252799, "Pattern: Trapper's Leather Hood", "Recipe, Leatherworking", 3 },
          { 252800, "Pattern: Defender's Leather Hood", "Recipe, Leatherworking", 3 },
          { 252801, "Pattern: Totemic Leather Hood", "Recipe, Leatherworking", 3 },
          { 252803, "Pattern: Wisdom's Leather Hood", "Recipe, Leatherworking", 3 },
          { 253938, "Pattern: Filigreed Pristine Leggings", "Recipe, Tailoring", 3 },
          { 253948, "Pattern: Filigreed Shining Leggings", "Recipe, Tailoring", 3 },
        } },
        { name = "Cookie", loot = {
          { 5198, "Cookie's Stirring Rod", "Ranged, Wand", 3 },
          { 5197, "Cookie's Tenderizer", "One-Hand, Mace", 3 },
          { 273298, "Lookie's Spyglass", "Trinket", 3 },
          { 251360, "Plans: Veteran's Gloves", "Recipe, Blacksmithing", 3 },
          { 252778, "Pattern: Trapper's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 252779, "Pattern: Defender's Leather Gloves", "Recipe, Leatherworking", 3 },
          { 253910, "Pattern: Filigreed Pearly Gown", "Recipe, Tailoring", 3 },
          { 253912, "Pattern: Filigreed Shining Gown", "Recipe, Tailoring", 3 },
          { 273102, "Blueprint: Cookie's Feast", "Blueprint", 2 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 10402, "Blackened Defias Boots", "Feet, Leather", 3 },
          { 10401, "Blackened Defias Gloves", "Hands, Leather", 3 },
          { 10400, "Blackened Defias Leggings", "Legs, Leather", 3 },
          { 1951, "Blackwater Cutlass", "One-Hand, Sword", 3 },
          { 1929, "Silk-threaded Trousers", "Legs, Cloth", 3 },
          { 1934, "Stonemason Trousers", "Legs, Leather", 3 },
          { 1936, "Goblin Screwdriver", "One-Hand, Dagger", 3 },
        } },
      },
      quests = {
        { id = 214, name = "Red Silk Bandanas", faction = "Alliance", level = 17, requires = 14, rewards = {
          { 2074, "Solid Shortblade", 2 },
          { 2089, "Scrimshaw Dagger", 2 },
          { 6094, "Piercing Axe", 2 },
          { 270005, "Monastic Hammer", 2 },
        } },
        { id = 168, name = "Collecting Memories", faction = "Alliance", level = 18, requires = 14, rewards = {
          { 2037, "Tunneler's Boots", 2 },
          { 2036, "Dusty Mining Gloves", 2 },
          { 270007, "Worn Miner's Waistcord", 2 },
        } },
        { id = 167, name = "Oh Brother...", faction = "Alliance", level = 20, requires = 15, rewards = {
          { 1893, "Miner's Revenge", 2 },
          { 270012, "Miner's Workgloves", 2 },
          { 270013, "Miner's Workboots", 2 },
        } },
        { id = 2040, name = "Underground Assault", faction = "Alliance", level = 20, requires = 15, rewards = {
          { 7606, "Polar Gauntlets", 2 },
          { 7607, "Sable Wand", 2 },
          { 270015, "Bravo's Armbands", 2 },
          { 270016, "Dreamer's Leggings", 2 },
        } },
        { id = 166, name = "The Defias Brotherhood", faction = "Alliance", level = 22, requires = 14, rewards = {
          { 6087, "Chausses of Westfall", 3 },
          { 2041, "Tunic of Westfall", 3 },
          { 2042, "Staff of Westfall", 3 },
        } },
        { id = 1806, name = "The Test of Righteousness", faction = "Alliance", level = 22, requires = 20, rewards = {
          { 6953, "Verigan's Fist", 3 },
        } },
      },
    },
    ["The Stockade"] = {
      level = "24-32",
      bosses = {
        { name = "Targorr the Dread", loot = {
          { 273805, "Blackrock Harness", "Chest, Leather", 3 },
          { 273804, "Executioner Mantle", "Shoulder, Leather", 3 },
          { 273806, "Dark Horde Band", "Finger", 3 },
          { 251380, "Plans: Veteran's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 251382, "Plans: Protector's Silvered Chain Helm", "Recipe, Blacksmithing", 3 },
          { 253942, "Pattern: Filigreed Flame Leggings", "Recipe, Tailoring", 3 },
        } },
        { name = "Kam Deepfury", loot = {
          { 2280, "Kam's Walking Stick", "Two-Hand, Staff", 3 },
          { 273807, "Demolition Girdle", "Waist, Leather", 3 },
          { 273808, "Bridgebreaker Bindings", "Wrist, Cloth", 3 },
          { 251379, "Plans: Crusader's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252825, "Pattern: Wisdom's Leather Leggings", "Recipe, Leatherworking", 3 },
        } },
        { name = "Hamhock", loot = {
          { 273809, "Hamhock's Cleaver", "Main Hand, Axe", 3 },
          { 273810, "Ogre Grips", "Hands, Mail", 3 },
          { 273811, "Repurposed Rack", "Off Hand, Shield", 3 },
          { 251377, "Plans: Protector's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
        } },
        { name = "Dextren Ward", loot = {
          { 273817, "Graverobber's Shovel", "Two-Hand, Mace", 3 },
          { 273819, "Boneslicer", "Two-Hand, Polearm", 3 },
          { 273820, "Nightskulker Ring", "Finger", 3 },
          { 251375, "Plans: Veteran's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 251376, "Plans: Guard's Silvered Chain Leggings", "Recipe, Blacksmithing", 3 },
          { 252820, "Pattern: Brawler's Leather Legguards", "Recipe, Leatherworking", 3 },
          { 252821, "Pattern: Trapper's Leather Legguards", "Recipe, Leatherworking", 3 },
        } },
        { name = "Bazil Thredd", loot = {
          { 273827, "Debt Collector", "Main Hand, Sword", 3 },
          { 273824, "Defias Jailbreakers", "Hands, Leather", 3 },
          { 273825, "Red Wool Cloak", "Back, Cloth", 3 },
          { 273829, "Concealed Hand Crossbow", "Ranged, Crossbow", 3 },
          { 252824, "Pattern: Stormrider's Leather Kilt", "Recipe, Leatherworking", 3 },
          { 253976, "Pattern: Filigreed Pristine Circlet", "Recipe, Tailoring", 3 },
          { 253986, "Pattern: Filigreed Shining Circlet", "Recipe, Tailoring", 3 },
        } },
        { name = "Bruegal Ironknuckle", loot = {
          { 3228, "Jimmied Handcuffs", "Wrist, Mail", 3 },
          { 2941, "Prison Shank", "One-Hand, Dagger", 3 },
          { 2942, "Iron Knuckles", "One-Hand, Fist Weapon", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 274092, "Sharpened Cutlery", "Thrown", 3 },
          { 1076, "Defias Renegade Ring", "Finger", 3 },
        } },
      },
      quests = {
        { id = 386, name = "What Comes Around...", faction = "Alliance", level = 25, requires = 22, rewards = {
          { 3400, "Lucine Longsword", 3 },
          { 1317, "Hardened Root Staff", 3 },
          { 270027, "Unknown Reward", 1 },
        } },
        { id = 377, name = "Crime and Punishment", faction = "Alliance", level = 26, requires = 22, rewards = {
          { 2033, "Ambassador's Boots", 3 },
          { 2906, "Darkshire Mail Leggings", 3 },
          { 270029, "Town Clerk's Mittens", 2 },
        } },
        { id = 378, name = "The Fury Runs Deep", faction = "Alliance", level = 27, requires = 25, rewards = {
          { 3562, "Belt of Vindication", 3 },
          { 1264, "Headbasher", 3 },
          { 270036, "Magistrate's Pantaloons", 3 },
        } },
      },
    },
    ["Wailing Caverns"] = {
      level = "15-24",
      bosses = {
        { name = "Lord Cobrahn", loot = {
          { 6460, "Cobrahn's Grasp", "Waist, Mail", 3 },
          { 10410, "Leggings of the Fang", "Legs, Leather", 3 },
          { 6465, "Robe of the Moccasin", "Chest, Cloth", 3 },
        } },
        { name = "Lady Anacondra", loot = {
          { 10412, "Belt of the Fang", "Waist, Leather", 3 },
          { 5404, "Serpent's Shoulders", "Shoulder, Leather", 3 },
          { 6446, "Snakeskin Bag", "Bag", 2 },
          { 273088, "Snake Eye Kaleidoscope", "Neck", 3 },
        } },
        { name = "Kresh", loot = {
          { 13245, "Kresh's Back", "Off Hand, Shield", 3 },
          { 6447, "Worn Turtle Shell Shield", "Off Hand, Shield", 3 },
          { 273084, "Cloak of Hermitic Bliss", "Back, Cloth", 3 },
        } },
        { name = "Lord Pythas", loot = {
          { 6472, "Stinging Viper", "One-Hand, Mace", 3 },
          { 6473, "Armor of the Fang", "Chest, Leather", 3 },
          { 273089, "Slither Cord", "Waist, Cloth", 3 },
        } },
        { name = "Skum", loot = {
          { 6449, "Glowing Lizardscale Cloak", "Back, Cloth", 3 },
          { 6448, "Tail Spike", "One-Hand, Dagger", 3 },
          { 273137, "Skum's Bucket", "Held In Off-hand", 3 },
        } },
        { name = "Lord Serpentis", loot = {
          { 6469, "Venomstrike", "Ranged, Bow", 3 },
          { 5970, "Serpent Gloves", "Hands, Cloth", 2 },
          { 10411, "Footpads of the Fang", "Feet, Leather", 3 },
          { 6459, "Savage Trodders", "Feet, Mail", 3 },
        } },
        { name = "Verdan the Everliving", loot = {
          { 6630, "Seedcloud Buckler", "Off Hand, Shield", 3 },
          { 6631, "Living Root", "Two-Hand, Staff", 3 },
          { 6629, "Sporid Cape", "Back, Cloth", 2 },
        } },
        { name = "Mutanus the Devourer", loot = {
          { 6461, "Slime-encrusted Pads", "Shoulder, Cloth", 3 },
          { 6627, "Mutant Scale Breastplate", "Chest, Mail", 3 },
          { 6463, "Deep Fathom Ring", "Finger", 3 },
          { 10441, "Glowing Shard", "Quest Item", 1 },
        } },
        { name = "Deviate Faerie Dragon", loot = {
          { 5243, "Firebelcher", "Ranged, Wand", 3 },
          { 6632, "Feyscale Cloak", "Back, Cloth", 3 },
          { 252781, "Pattern: Stormrider's Leather Gloves", "Recipe, Leatherworking", 3 },
        } },
        { name = "Trash Drops", trash = true, loot = {
          { 10413, "Gloves of the Fang", "Hands, Leather", 3 },
        } },
      },
      quests = {
        { id = 1486, name = "Deviate Hides", faction = "Both", level = 17, requires = 13, rewards = {
          { 6480, "Slick Deviate Leggings", 2 },
          { 918, "Deviate Hide Pack", 1 },
        } },
        { id = 1487, name = "Deviate Eradication", faction = "Both", level = 21, requires = 15, rewards = {
          { 6476, "Pattern: Deviate Scale Belt", 2 },
          { 8071, "Sizzle Stick", 2 },
          { 6481, "Dagmire Gauntlets", 2 },
        } },
        { id = 914, name = "Leaders of the Fang", faction = "Horde", level = 22, requires = 10, rewards = {
          { 6505, "Crescent Staff", 3 },
          { 6504, "Wingblade", 3 },
          { 270018, "Hammerbone", 3 },
        } },
        { id = 962, name = "Serpentbloom", faction = "Horde", level = 18, requires = 14, rewards = {
          { 10919, "Apothecary Gloves", 2 },
          { 270008, "Heat Resistant Mitts", 2 },
          { 270009, "Safety Boots", 2 },
        } },
      },
    },
  },
}
