#!/usr/bin/env python3
"""Build Gearwright/Data/ClassStats.lua from Forever's PlayerExpectedStat table.

Forever ships, per class and level, how much crit one Agility gives, how much
spell crit one Intellect gives, base mana and health per Stamina. This is the
game's own data, so the addon reads it instead of guessing between two points.

The CSV is a copy of the DB2 table from wago.tools:
  https://wago.tools/db2/PlayerExpectedStat/csv?build=1.60.1.70245

Usage:
  python tools/classstats_from_wago.py data/reference/PlayerExpectedStat-1.60.1.70245.csv
  python tools/classstats_from_wago.py <csv> --check   # exit 1 if the Lua file is stale
"""
import argparse
import csv
import sys
from pathlib import Path

CLASSES = {
    1: "WARRIOR", 2: "PALADIN", 3: "HUNTER", 4: "ROGUE", 5: "PRIEST",
    7: "SHAMAN", 8: "MAGE", 9: "WARLOCK", 11: "DRUID",
}
MAX_LEVEL = 60
OUT = Path(__file__).resolve().parent.parent / "Gearwright" / "Data" / "ClassStats.lua"


def per_point(fraction):
    """Points of a stat per 1%, from the table's fraction per point (0 = none)."""
    f = float(fraction)
    return round(1 / (f * 100), 2) if f > 0 else 0


def num(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return s or "0"


def build(csv_path):
    rows = {}
    for r in csv.DictReader(open(csv_path, newline="", encoding="utf-8")):
        cls, level = CLASSES.get(int(r["ClassID"])), int(r["Level"])
        if not cls or level > MAX_LEVEL or r["ContentSetID"] != "0":
            continue
        rows.setdefault(cls, {})[level] = r

    out = [
        "-- Gearwright: per-class, per-level stat conversions from Forever's own",
        "-- PlayerExpectedStat table (build 1.60.1.70245, via wago.tools).",
        "-- GENERATED by tools/classstats_from_wago.py; do not edit by hand.",
        "--",
        "-- agiPerCrit[level]      Agility per 1% melee/ranged crit",
        "-- intPerSpellCrit[level] Intellect per 1% spell crit (0 = no mana)",
        "-- baseMana[level]        mana before Intellect",
        "-- hpPerSta               health per Stamina",
        "--",
        "-- Checked against the beta's character sheet: Rogue 19 (7.6 Agility per 1%)",
        "-- and Priest 12 (9.5 Intellect per 1%).",
        "local _, ns = ...",
        "",
        "ns.Data.CLASS_STATS = {",
    ]
    for cls in sorted(rows):
        lv = rows[cls]
        missing = [l for l in range(1, MAX_LEVEL + 1) if l not in lv]
        if missing:
            sys.exit(f"{cls}: no row for levels {missing}")
        series = lambda f: ", ".join(f(lv[l]) for l in range(1, MAX_LEVEL + 1))
        hp = {lv[l]["HPPerStamina"] for l in lv}
        out += [
            f"  {cls} = {{",
            f"    hpPerSta = {hp.pop() if len(hp) == 1 else 10},",
            f"    agiPerCrit = {{ {series(lambda r: num(per_point(r['CritPerAgility'])))} }},",
            f"    intPerSpellCrit = {{ {series(lambda r: num(per_point(r['SpellCritPerIntellect'])))} }},",
            f"    baseMana = {{ {series(lambda r: r['BaseMana'])} }},",
            "  },",
        ]
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv")
    ap.add_argument("--check", action="store_true", help="only compare with the existing file")
    args = ap.parse_args()
    text = build(args.csv)
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit(f"{OUT} is out of date; rerun without --check")
        print("ClassStats.lua is up to date")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
