#!/usr/bin/env python3
"""Build Gearwright/Data/Crafted.lua from GearwrightProbe profession scans.

The probe saves every recipe of each profession window it sees, learned or
not, with the item it makes. This merges the scans of any number of exports
into one table of craftable items, so Gearwright can point out a crafted
upgrade even when you don't have that profession ("have it crafted").

Which of these items you can wear and whether they're upgrades is decided at
runtime; professions that only make consumables are left out to keep it small.

Usage:
  python tools/crafted_from_probe.py data/probe/*.json
"""
import argparse
import json
import sys
from pathlib import Path

SKIP = {"Cooking", "First Aid", "Skinning", "Fishing", "Mining", "Herbalism", "Alchemy"}


def scans(path):
    db = json.loads(Path(path).read_text())
    for key, scan in (db.get("scans") or db).items():
        if key.startswith("tradeskill:") and isinstance(scan, dict):
            yield key.split(":", 1)[1], scan


def collect(paths):
    by_prof = {}  # profession -> {itemID: (recipeID, name)}
    for path in paths:
        for prof, scan in scans(path):
            if prof in SKIP:
                continue
            items = by_prof.setdefault(prof, {})
            for r in scan.get("recipes") or []:
                item = r.get("outputItemID") or r.get("itemID")
                if isinstance(item, int) and item not in items:
                    items[item] = (r.get("recipeID"), r.get("name"))
    return by_prof


def lua_str(s):
    return "nil" if s is None else '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("probe_json", nargs="+")
    ap.add_argument("-o", "--out", default="Gearwright/Data/Crafted.lua")
    args = ap.parse_args()

    by_prof = collect(args.probe_json)
    profs = sorted(by_prof)
    out = [
        "-- Gearwright: items each profession can make, from GearwrightProbe scans.",
        "-- Generated by tools/crafted_from_probe.py. Do not edit by hand: rerun the tool",
        "-- with more exports instead.",
        "--",
        "-- recipes: { profession index, recipeID, itemID, recipe name }",
        "local _, ns = ...",
        "",
        "ns.Data.CRAFTED = {",
        "  professions = { " + ", ".join(lua_str(p) for p in profs) + " },",
        "  recipes = {",
    ]
    n = 0
    for i, prof in enumerate(profs, 1):
        for item, (rid, name) in sorted(by_prof[prof].items()):
            out.append(f"    {{ {i}, {rid}, {item}, {lua_str(name)} }},")
            n += 1
    out += ["  },", "}"]
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {n} recipes from {', '.join(profs) or 'no professions'} to {args.out}")


if __name__ == "__main__":
    sys.exit(main())
