#!/usr/bin/env python3
"""Build Gearwright/Data/Enchants.lua from a GearwrightProbe Enchanting scan.

The probe saves each recipe's spell description ("Permanently enchant bracers
to give +5 Agility."). This reads the stat and amount out of that text, so the
addon can score every enchant with the same weights it uses for gear.

Enchants whose effect is a proc, a spell-power bonus or a resistance are left
out: there's no stat weight for them yet. They are listed when you run this.

Usage:
  python tools/enchants_from_probe.py data/probe/2026-10-03-professions.json
"""
import argparse
import json
import re
import sys
from pathlib import Path

# "Enchant <category> - <name>" -> category key used by the addon
CATEGORIES = {
    "Chest": "chest", "Bracer": "bracer", "Gloves": "gloves", "Boots": "boots",
    "Cloak": "cloak", "Necklace": "neck", "Weapon": "weapon", "2H Weapon": "2h",
    "Shield": "shield", "Off-Hand": "offhand",
}

STAT_WORDS = {
    "agility": "agi", "strength": "str", "stamina": "sta",
    "intellect": "int", "spirit": "spi",
}

# Damage bonuses only against one creature type aren't worth a general score.
SLAYER = re.compile(r"beasts|elementals?|demons|mechanical|undead", re.I)
# Procs and timed buffs: "chance", "often", "for 15 sec" etc.
PROC = re.compile(r"chance per hit|chance to (?:grant|trigger|acquire)|\boften\b|\d+ sec\b", re.I)


def parse(desc):
    """Stats from an enchant description, or {} when nothing is scoreable."""
    text = (desc or "").lower()
    if not text or PROC.search(text):
        return {}
    stats = {}

    m = re.search(r"\+?(\d+) to all stats|all stats by (\d+)", text)
    if m:
        n = int(m.group(1) or m.group(2))
        for key in STAT_WORDS.values():
            stats[key] = n

    for word, key in STAT_WORDS.items():
        m = (re.search(r"\+?(\d+) (?:to )?" + word, text)
             or re.search(word + r"(?: of the (?:wearer|bearer))? by (\d+)", text))
        if m:
            stats[key] = int(m.group(1))

    m = re.search(r"do \+?(\d+) (?:additional )?(?:points? of )?damage", text)
    if m and not SLAYER.search(text):
        stats["weaponDamage"] = int(m.group(1))

    for pattern, key in (
        (r"(\d+)% critical strike chance", "crit"),
        (r"\+?(\d+)% attack and casting speed", "haste"),
        (r"(\d+)% chance to dodge", "dodge"),
        (r"\+?(\d+)% chance to block", "block"),
        (r"\+?(\d+) defense", "defense"),
        (r"defense skill (?:of the wearer )?(?:is increased )?by (\d+)", "defense"),
        (r"(\d+) additional armor", "armor"),
        (r"armor by (\d+)", "armor"),
    ):
        m = re.search(pattern, text)
        if m and key not in stats:
            stats[key] = int(m.group(1))
    return stats


def enchant_recipes(db):
    scans = db.get("scans", db)
    scan = scans.get("tradeskill:Enchanting")
    if not scan:
        sys.exit("no tradeskill:Enchanting scan in this file (open Enchanting with the probe loaded)")
    return scan["recipes"], scan.get("at", "?")


def lua_stats(stats):
    return "{ " + ", ".join(f"{k} = {v}" for k, v in sorted(stats.items())) + " }"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("probe_json")
    ap.add_argument("-o", "--out", default="Gearwright/Data/Enchants.lua")
    args = ap.parse_args()

    recipes, at = enchant_recipes(json.loads(Path(args.probe_json).read_text()))
    rows, skipped = [], []
    for r in recipes:
        m = re.match(r"Enchant (.+?) - (.+)$", r.get("name", ""))
        if not m or m.group(1) not in CATEGORIES:
            continue
        stats = parse(r.get("desc"))
        if not stats:
            skipped.append(r["name"])
            continue
        rows.append((CATEGORIES[m.group(1)], m.group(2), r["recipeID"], stats))

    rows.sort(key=lambda row: (row[0], row[1], row[2]))
    out = [
        "-- Gearwright: enchant effects, read from the Forever beta's Enchanting recipes.",
        f"-- Generated by tools/enchants_from_probe.py from a probe scan taken {at}.",
        "-- Do not edit by hand: rerun the tool on a newer scan instead.",
        "--",
        "-- cat:   chest bracer gloves boots cloak neck weapon (any melee weapon)",
        "--        2h (two-handed weapon) shield offhand (held in off hand)",
        "-- id:    the recipe's spell ID",
        "-- stats: Gearwright stat keys (Data/Stats.lua); crit/haste/dodge/block in %,",
        "--        weaponDamage = flat damage added to each weapon swing",
        "local _, ns = ...",
        "",
        "ns.Data.ENCHANTS = {",
    ]
    for cat, name, rid, stats in rows:
        out.append(f'  {{ cat = "{cat}", name = "{name}", id = {rid}, stats = {lua_stats(stats)} }},')
    out.append("}")
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {len(rows)} enchants to {args.out}")
    if skipped:
        print(f"left out {len(skipped)} with no scoreable stat:")
        for name in skipped:
            print("  " + name)


if __name__ == "__main__":
    main()
