#!/usr/bin/env python3
"""Build Gearwright/Data/DungeonJournal.lua from Forever Dungeon Journal's data.

Forever Dungeon Journal (FDJ) is an addon by Exehn with boss loot, trash drops
and dungeon quests (and their rewards) for every Forever dungeon. Exehn gave
permission (in game, 2026-10-04) for Gearwright to use its data as long as he
is credited, so Gearwright ships a copy and works without FDJ installed. When
FDJ is installed, Gearwright reads its live table instead (it may be newer).

This runs FDJ's Data/Dungeons.lua (with lupa) and keeps only what Gearwright
uses: each dungeon's level range, its bosses' loot, and its quests' reward
items with faction and level.

Usage:
  python tools/fdj_import.py path/to/ForeverDungeonJournal        (the addon folder)
  python tools/fdj_import.py ForeverDungeonJournal-1.4.4.zip
"""
import argparse
import re
import sys
import tempfile
import zipfile
from pathlib import Path

from lupa import lua51


def find_addon(path):
    p = Path(path)
    if p.suffix == ".zip":
        tmp = Path(tempfile.mkdtemp())
        zipfile.ZipFile(p).extractall(tmp)
        p = tmp
    hits = list(p.rglob("ForeverDungeonJournal.toc"))
    if not hits:
        sys.exit(f"no ForeverDungeonJournal.toc under {path}")
    return hits[0].parent


def lua_str(s):
    return "nil" if s is None else '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def items(t, fields):
    out = []
    for item in (t or {}).values():
        if hasattr(item, "values"):
            v = list(item.values())
            if v and isinstance(v[0], int):
                out.append(v[: len(fields)])
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("fdj", help="the ForeverDungeonJournal addon folder or its zip")
    ap.add_argument("-o", "--out", default="Gearwright/Data/DungeonJournal.lua")
    args = ap.parse_args()

    root = find_addon(args.fdj)
    toc = (root / "ForeverDungeonJournal.toc").read_text(errors="replace")
    version = (re.search(r"^## Version:\s*(\S+)", toc, re.M) or [None, "?"])[1]
    L = lua51.LuaRuntime(unpack_returned_tuples=True)
    fdj = L.eval("{ Constants = { ALBA_FAIRMOON_LOCATION = 'Alba Fairmoon, Sentinel Hill inn, Westfall' } }")
    run = L.eval("function(src, name, ns) return assert(loadstring(src, name))('ForeverDungeonJournal', ns) end")
    run((root / "Data" / "Dungeons.lua").read_text(), "@Dungeons.lua", fdj)

    lines = [
        "-- Gearwright: dungeon loot and dungeon quest rewards for Forever.",
        "--",
        f"-- Data from Forever Dungeon Journal {version} by Exehn, used with his permission",
        "-- (given in game, 2026-10-04) on the condition that he is credited. Thank you, Exehn!",
        "-- Generated by tools/fdj_import.py; do not edit by hand. When Forever Dungeon",
        "-- Journal is installed, Gearwright reads its live data instead of this copy.",
        "--",
        "-- dungeons[name] = { level = \"13-20\",",
        "--   bosses = { { name, trash = true?, loot = { { itemID, name, slot, quality } } } },",
        "--   quests = { { id, name, faction, level, requires, rewards = { { itemID, name, quality } } } } }",
        "local _, ns = ...",
        "",
        "ns.Data.DUNGEON_JOURNAL = {",
        f"  source = {lua_str('Forever Dungeon Journal ' + version + ' by Exehn')},",
        "  dungeons = {",
    ]
    n_items = n_quests = 0
    for name in sorted(fdj.DB.keys()):
        d = fdj.DB[name]
        lines.append(f"    [{lua_str(name)}] = {{")
        lines.append(f"      level = {lua_str(d.level)},")
        lines.append("      bosses = {")
        for boss in (d.bosses or {}).values():
            loot = items(boss.loot, ("id", "name", "slot", "quality"))
            n_items += len(loot)
            trash = ", trash = true" if boss.trash else ""
            lines.append(f"        {{ name = {lua_str(boss.name)}{trash}, loot = {{")
            for it in loot:
                lines.append("          { " + ", ".join(str(x) if isinstance(x, int) else lua_str(x) for x in it) + " },")
            lines.append("        } },")
        lines.append("      },")
        lines.append("      quests = {")
        for q in (d.quests or {}).values():
            rewards = items(q.rewardItems, ("id", "name", "quality"))
            if not rewards:
                continue
            n_quests += 1
            lines.append(f"        {{ id = {q.id or 'nil'}, name = {lua_str(q.name)}, faction = {lua_str(q.faction)}, "
                         f"level = {q.level or 'nil'}, requires = {q.requires or 'nil'}, rewards = {{")
            for it in rewards:
                lines.append("          { " + ", ".join(str(x) if isinstance(x, int) else lua_str(x) for x in it) + " },")
            lines.append("        } },")
        lines.append("      },")
        lines.append("    },")
    lines += ["  },", "}"]
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"wrote {len(list(fdj.DB.keys()))} dungeons, {n_items} loot entries, {n_quests} quests with rewards to {args.out}")


if __name__ == "__main__":
    sys.exit(main())
