#!/usr/bin/env python3
"""Build Gearwright/Data/DungeonLoot.lua from GearwrightProbe loot logs.

The probe records every loot window: the item, the NPC that dropped it (ID and
name) and the instance. This keeps the drops made inside instances, merges any
number of exports, and writes them as Gearwright's own dungeon loot table.

Common (white/grey) items are left out; Gearwright decides at runtime which of
the rest your class and spec can use.

Usage:
  python tools/loot_from_probe.py data/probe/*.json
"""
import argparse
import json
import sys
from pathlib import Path

MIN_QUALITY = 2  # uncommon and better; unknown quality is kept


def load(path):
    db = json.loads(Path(path).read_text())
    return (db.get("scans") or {}).get("loot") or {}


def collect(paths):
    drops = {}  # (itemID, dungeon, npc) -> row
    for path in paths:
        for item_id, rec in (load(path).get("items") or {}).items():
            quality = rec.get("quality")
            if isinstance(quality, int) and quality < MIN_QUALITY:
                continue
            for src, e in (rec.get("from") or {}).items():
                if not e.get("instance"):
                    continue
                npc = src.split(":", 1)[1] if src.startswith("Creature:") else None
                key = (int(item_id), e.get("where"), npc)
                row = drops.setdefault(key, {
                    "itemID": int(item_id), "name": rec.get("name"), "quality": quality,
                    "dungeon": e.get("where"), "npcID": int(npc) if npc and npc.isdigit() else None,
                    "from": e.get("name"), "count": 0,
                })
                row["count"] += e.get("count") or 1
                row["from"] = row["from"] or e.get("name")
    return sorted(drops.values(), key=lambda r: (str(r["dungeon"]), str(r["from"]), r["itemID"]))


def lua_str(s):
    return "nil" if s is None else '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("probe_json", nargs="+")
    ap.add_argument("-o", "--out", default="Gearwright/Data/DungeonLoot.lua")
    args = ap.parse_args()

    rows = collect(args.probe_json)
    out = [
        "-- Gearwright: dungeon drops seen in game, from GearwrightProbe loot logs.",
        "-- Generated by tools/loot_from_probe.py. Do not edit by hand: rerun the tool",
        "-- with more exports instead.",
        "--",
        "-- from: the NPC's name when it was targeted while looting; count: times seen.",
        "local _, ns = ...",
        "",
        "ns.Data.DUNGEON_LOOT = {",
    ]
    for r in rows:
        out.append(f'  {{ itemID = {r["itemID"]}, name = {lua_str(r["name"])}, dungeon = {lua_str(r["dungeon"])}, '
                   f'from = {lua_str(r["from"])}, npcID = {r["npcID"] if r["npcID"] else "nil"}, count = {r["count"]} }},')
    out.append("}")
    Path(args.out).write_text("\n".join(out) + "\n")
    print(f"wrote {len(rows)} drops to {args.out}")


if __name__ == "__main__":
    sys.exit(main())
