#!/usr/bin/env python3
"""Build Gearwright/Data/<Class>/Trainer.lua from GearwrightProbe trainer captures.

Each class trainer capture lists the trainer's spells with the level they
unlock at (and, in newer captures, their cost). This merges the captures of
the trainers you name into the class's spell list for Gearwright's train
reminders, plus where those trainers stand.

Spells you had already learned report level 0 on Forever, so they're only
kept when another capture (e.g. a lower-level character's) or a checked list
(--verified, e.g. data/verified/rogue-trainer-low-levels.json) gives their
level. Gearwright fills in the rest by itself from trainer visits in game.

Usage:
  python tools/trainer_from_probe.py --class ROGUE --trainer Fenthwick \\
      --trainer "Lord Tony Romano" --city "Lord Tony Romano=Stormwind" \\
      --verified data/verified/rogue-trainer-low-levels.json data/probe/*.json
"""
import argparse
import json
import re
import sys
from pathlib import Path


def lua_str(s):
    return "nil" if s is None else '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def first(v):
    if isinstance(v, list):
        return v[0] if v else None
    return v


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("probe_json", nargs="+")
    ap.add_argument("--class", dest="cls", required=True)
    ap.add_argument("--trainer", action="append", required=True)
    ap.add_argument("--city", action="append", default=[], help='"Trainer=City" for captures without a position')
    ap.add_argument("--verified", action="append", default=[], help="checked spell list (name, rank, level)")
    ap.add_argument("-o", "--out")
    args = ap.parse_args()
    cities = dict(c.split("=", 1) for c in args.city)
    out_path = args.out or f"Gearwright/Data/{args.cls.capitalize()}/Trainer.lua"

    spells, trainers = {}, {}
    for path in args.probe_json:
        scans = json.loads(Path(path).read_text()).get("scans") or {}
        for name in args.trainer:
            scan = scans.get("trainer:" + name)
            if not scan:
                continue
            npc = re.match(r"^\w+-[^-]*-[^-]*-[^-]*-[^-]*-(\d+)", scan.get("npc") or "")
            t = trainers.setdefault(name, {"name": name, "city": cities.get(name)})
            if npc:
                t["npcID"] = int(npc.group(1))
            if scan.get("x") is not None:
                t.update(mapID=first((scan.get("map") or {}).get("values")), x=round(scan["x"], 3),
                         y=round(scan["y"], 3), city=scan.get("zone"))
            for svc in scan.get("services") or []:
                v = svc.get("values") or []
                if len(v) < 5 or not isinstance(v[0], str):
                    continue
                spell, level, rank = v[0], v[3], v[4] or ""
                level = first((svc.get("level") or [None])) or level
                cost = first(svc.get("cost"))
                key = (spell, rank)
                row = spells.setdefault(key, {"name": spell, "rank": rank, "level": 0, "cost": None})
                if isinstance(level, int) and level > 0:
                    row["level"] = level
                if isinstance(cost, int) and cost > 0:
                    row["cost"] = cost

    # Checked lists fill in levels the captures don't have; a capture still wins.
    for path in args.verified:
        for v in json.loads(Path(path).read_text()).get("spells") or []:
            row = spells.setdefault((v["name"], v.get("rank") or ""),
                                    {"name": v["name"], "rank": v.get("rank") or "", "level": 0, "cost": None})
            if not row["level"]:
                row["level"] = v["level"]
            if not row["cost"] and v.get("cost"):
                row["cost"] = v["cost"]

    rows = sorted((r for r in spells.values() if r["level"] > 0), key=lambda r: (r["level"], r["name"], r["rank"]))
    lines = [
        f"-- Gearwright: {args.cls.capitalize()} trainer spells, from GearwrightProbe trainer captures.",
        "-- Generated by tools/trainer_from_probe.py. Do not edit by hand: rerun the tool",
        "-- with more captures instead. Gearwright adds what it reads at trainers in game.",
        "--",
        "-- spells: { name, rank (\"Rank 3\" or \"\"), level it unlocks at, cost in copper (if known) }",
        "-- trainers: where the class trainers stand (uiMapID, 0-1 position)",
        "local _, ns = ...",
        f"ns.Data.{args.cls} = ns.Data.{args.cls} or {{}}",
        "",
        f"ns.Data.{args.cls}.trainer = {{",
        "  spells = {",
    ]
    for r in rows:
        cost = r["cost"] if r["cost"] else "nil"
        lines.append(f"    {{ name = {lua_str(r['name'])}, rank = {lua_str(r['rank'])}, level = {r['level']}, cost = {cost} }},")
    lines += ["  },", "  trainers = {"]
    for name in args.trainer:
        t = trainers.get(name)
        if not t:
            continue
        pos = (f", mapID = {t['mapID']}, x = {t['x']}, y = {t['y']}" if t.get("mapID") else "")
        lines.append(f"    {{ npcID = {t.get('npcID', 'nil')}, name = {lua_str(name)}, city = {lua_str(t.get('city'))}{pos} }},")
    lines += ["  },", "}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"wrote {len(rows)} spells and {len(trainers)} trainers to {out_path}")


if __name__ == "__main__":
    sys.exit(main())
